version: '3.7'
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "1884:1884"
      - "443:443"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/certs:/etc/mosquitto/certs
