version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "1884:1884"    # WebSockets
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/certs:/etc/mosquitto/certs
      - ./mosquitto/passwd:/etc/mosquitto/passwd
    networks:
      - default
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"      # HTTP voor test zonder SSL
      - "443:443"    # HTTPS
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs   # Voeg de certificaten toe
    networks:
      - default

networks:
  default:
    driver: bridge